/* Generated By:JavaCC: Do not edit this line. TiggerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TiggerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int EOL = 6;
  /** RegularExpression Id. */
  int PRINT = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int THEN = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int VAR = 11;
  /** RegularExpression Id. */
  int LET = 12;
  /** RegularExpression Id. */
  int IN = 13;
  /** RegularExpression Id. */
  int END = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int DO = 16;
  /** RegularExpression Id. */
  int FOR = 17;
  /** RegularExpression Id. */
  int TO = 18;
  /** RegularExpression Id. */
  int STRING = 19;
  /** RegularExpression Id. */
  int INT = 20;
  /** RegularExpression Id. */
  int BOOL = 21;
  /** RegularExpression Id. */
  int QUIT = 22;
  /** RegularExpression Id. */
  int IDENTIFIER = 23;
  /** RegularExpression Id. */
  int TEXT = 24;
  /** RegularExpression Id. */
  int LETTER = 25;
  /** RegularExpression Id. */
  int PLUS = 26;
  /** RegularExpression Id. */
  int MINUS = 27;
  /** RegularExpression Id. */
  int STAR = 28;
  /** RegularExpression Id. */
  int SLASH = 29;
  /** RegularExpression Id. */
  int OPAREN = 30;
  /** RegularExpression Id. */
  int CPAREN = 31;
  /** RegularExpression Id. */
  int OBRACK = 32;
  /** RegularExpression Id. */
  int CBRACK = 33;
  /** RegularExpression Id. */
  int EQ = 34;
  /** RegularExpression Id. */
  int NEQ = 35;
  /** RegularExpression Id. */
  int GT = 36;
  /** RegularExpression Id. */
  int GEQ = 37;
  /** RegularExpression Id. */
  int LT = 38;
  /** RegularExpression Id. */
  int LEQ = 39;
  /** RegularExpression Id. */
  int AFFECTATION = 40;
  /** RegularExpression Id. */
  int SEP = 41;
  /** RegularExpression Id. */
  int QUOTE = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<NUMBER>",
    "<DIGIT>",
    "\"\\n\"",
    "\"print\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"var\"",
    "\"let\"",
    "\"in\"",
    "\"end\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"to\"",
    "\"string\"",
    "\"int\"",
    "\"bool\"",
    "\"quit\"",
    "<IDENTIFIER>",
    "<TEXT>",
    "<LETTER>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\":=\"",
    "\",\"",
    "\"\\\"\"",
  };

}
